### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by arulpr** [JasonWei512/code-radio-cli#25] opened 2024-02-08 04:19 UTC
Got the following response when I tried to stream today

```
Error: Server-Sent Events Error: HttpStream(
    hyper::Error(
        Connect,
        Custom {
            kind: Other,
            error: Custom {
                kind: InvalidData,
                error: InvalidSCT(
                    UnknownLog,
                ),
            },
        `},`
    ),
)
```

**Comment by JasonWei512** [comment] 2024-02-08 05:01
Duplicate of https://github.com/JasonWei512/code-radio-cli/issues/23 .
Please upgrade to [1.0.5](https://github.com/JasonWei512/code-radio-cli/releases/tag/v1.0.5) .

**Closed as completed by JasonWei512** 2024-02-08 05:01 UTC
